# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Factory < Formula
  desc "Run agent workflows as a DAG of steps, one sandbox per step"
  homepage "https://github.com/tdensmore/factory"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tdensmore/homebrew-factory/releases/download/v0.1.1/factory_0.1.1_darwin_amd64.tar.gz"
      sha256 "e145feabce64222cc3f61a62121e335c3763c003eda02ed1c83dfe7ddfe4f3b8"

      define_method(:install) do
        bin.install "factory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tdensmore/homebrew-factory/releases/download/v0.1.1/factory_0.1.1_darwin_arm64.tar.gz"
      sha256 "e40090bf9531755dc9cf6659ced7acd6cd4b2a2c38847aec6ffae9f1103ebceb"

      define_method(:install) do
        bin.install "factory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tdensmore/homebrew-factory/releases/download/v0.1.1/factory_0.1.1_linux_amd64.tar.gz"
      sha256 "fc0d38da10ff4b21a5671d18263c7bf0ab20e74c6ee24371d60f6540c5bc86ad"
      define_method(:install) do
        bin.install "factory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tdensmore/homebrew-factory/releases/download/v0.1.1/factory_0.1.1_linux_arm64.tar.gz"
      sha256 "374af1d6e2a2fce96ff91ed0bd44321bd127590d6c60a679c76cea0ead2da031"
      define_method(:install) do
        bin.install "factory"
      end
    end
  end

  def caveats
    <<~EOS
      factory drives the `sbx` CLI (Docker Sandboxes) to create the sandbox
      each workflow step runs in; it needs Docker Desktop and sbx installed
      separately. Run `factory doctor` to check both before your first
      `factory run`.
    EOS
  end

  test do
    system "#{bin}/factory", "version"
  end
end
