# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Factory < Formula
  desc "Run agent workflows as a DAG of steps, one sandbox per step"
  homepage "https://github.com/tdensmore/factory"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tdensmore/homebrew-factory/releases/download/v0.2.0/factory_0.2.0_darwin_amd64.tar.gz"
      sha256 "63bb01a9ee75591cd7429e039329f1b4ce2645e501dfb6cf17d811c8b7eac778"

      define_method(:install) do
        bin.install "factory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tdensmore/homebrew-factory/releases/download/v0.2.0/factory_0.2.0_darwin_arm64.tar.gz"
      sha256 "e71ac80875593e47c64419543016ef8d3c98a1361435e6be982117c757e636be"

      define_method(:install) do
        bin.install "factory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tdensmore/homebrew-factory/releases/download/v0.2.0/factory_0.2.0_linux_amd64.tar.gz"
      sha256 "81bd6729f49844ff3fa668268ade288a534281e9e1d85bcfa883c6b5f965a1f7"
      define_method(:install) do
        bin.install "factory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tdensmore/homebrew-factory/releases/download/v0.2.0/factory_0.2.0_linux_arm64.tar.gz"
      sha256 "c6a761948b5648927f270b3df025ec0b51eafe7b3aa3080725f974f6f40a3fd9"
      define_method(:install) do
        bin.install "factory"
      end
    end
  end

  def caveats
    <<~EOS
      factory drives the `sbx` CLI (Docker Sandboxes) to create the sandbox
      each workflow step runs in; it needs Docker Desktop and sbx installed
      separately. Run `factory doctor` to check both before your first
      `factory run`.
    EOS
  end

  test do
    system "#{bin}/factory", "version"
  end
end
