# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Factory < Formula
  desc "Run agent workflows as a DAG of steps, one sandbox per step"
  homepage "https://github.com/tdensmore/factory"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tdensmore/factory/releases/download/v0.1.0/factory_0.1.0_darwin_amd64.tar.gz"
      sha256 "fb73747390675e846e8f833e18a81e2218e8747b2c030079522adcb9618dee27"

      define_method(:install) do
        bin.install "factory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tdensmore/factory/releases/download/v0.1.0/factory_0.1.0_darwin_arm64.tar.gz"
      sha256 "3bcc0fea649a45c9baaf464fd07f749b359df20aec8933582b6311e8e28059bb"

      define_method(:install) do
        bin.install "factory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tdensmore/factory/releases/download/v0.1.0/factory_0.1.0_linux_amd64.tar.gz"
      sha256 "be4f2a606c02e24636c24f5ef70cde37ba1132d4ebccf4b2c315986fd1a22e2d"
      define_method(:install) do
        bin.install "factory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tdensmore/factory/releases/download/v0.1.0/factory_0.1.0_linux_arm64.tar.gz"
      sha256 "92a41160b0e862260166f15b153c88fd61a5defcc86aad981fa83a97bfeb18ec"
      define_method(:install) do
        bin.install "factory"
      end
    end
  end

  def caveats
    <<~EOS
      factory drives the `sbx` CLI (Docker Sandboxes) to create the sandbox
      each workflow step runs in; it needs Docker Desktop and sbx installed
      separately. Run `factory doctor` to check both before your first
      `factory run`.
    EOS
  end

  test do
    system "#{bin}/factory", "version"
  end
end
